spring:
  application:
    name: api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080}/realms/reports-realm
          jwk-set-uri: ${JWK_URI:http://keycloak:8080}/realms/reports-realm/protocol/openid-connect/certs
server:
  port: 8080

